### ISSUE TITLE
Setting up for Mix `npm run watch/hot`

### ISSUE THREAD

**Issue by jofrysutanto** [nanobox-quickstarts/nanobox-laravel#11]
Looking at the work-in-progress for Nanobox Laravel 5.5 it's indicating that `npm run dev` will be supported.

https://github.com/nanobox-quickstarts/nanobox-laravel/blob/9431db6a5c52990fd5b4b2a3667db9e468518c55/boxfile.yml#L37

For us who prefers to also run Browsersync or HMR what will be the best way to go about it?

What I have tried is running two separate `nanobox run`, one for serving the web server and another to run `npm run watch`, which hasn't been working. With the following boxfile.yml

```
run.config:
  # install php and associated runtimes
  engine: php

  fs_watch: true

  extra_packages:
    - nodejs

  extra_path_dirs:
    - node_modules/.bin

  extra_steps:
    - yarn

  build_triggers:
    - package.json
    - composer.json

  cache_dirs:
    - vendor
    - node_modules

  # php engine configuration (php version, extensions, etc)
  engine.config:

    # sets the php version to 7.0
    runtime: php-7.0

    # use nginx
    webserver: nginx

    # public directory
    document_root: public

    # enables php extensions
    extensions:
      - pdo
      - pdo_mysql
      - mbstring
      - tokenizer
      - session
      - zip
      - dom
      - xml
      - ctype
      - xmlwriter

#
deploy.config:
  before_live:
    web.main:
      - php artisan migrate --force
      - mkdir -p storage/framework/{sessions,cache,views}

# add a MySQL database
data.db:
  image: nanobox/mysql:5.6

# add a local storage database
data.storage:
  image: nanobox/unfs:0.9

# add a web server
web.main:
  start: php-server

  # add writable dirs to your web component
  writable_dirs:
    - bootstrap/cache
    - node_modules

  # the path to a logfile you want streamed to the nanobox dashboard
  log_watch:
    laravel[error]: /app/storage/logs/laravel.log

  # directories to be stored in the data.storage component
  network_dirs:
    data.storage:
      - storage
```

Running `npm run hot` seem to expect access to localhost:3000 or 172.21.xx.xx:3000, but accessing this url does not work at all. Does this have something to do with the fact that nanobox only listen to 80 (and mapped to 8080)?

A pointer will be great at this point.

PS. Nanobox is an exciting platform, awesome work guys.
